version: '3.8'

services:
  backend:
    image: trangh/nipah-ebs-monitor-fullstack-backend:v1.0.1
    volumes:
      - ./backend:/app
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    image: trangh/nipah-ebs-monitor-fullstack-frontend:v1.0.1
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend